# Generated by Django 5.0.3 on 2026-03-16 16:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("freelance", "Freelance"),
                            ("investment", "Investment"),
                            ("business", "Business"),
                            ("gift", "Gift"),
                            ("bonus", "Bonus"),
                            ("other", "Other"),
                        ],
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Income Category",
                "verbose_name_plural": "Income Categories",
            },
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("received_date", models.DateField(default=datetime.date.today)),
                ("source", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[("once", "One-time"), ("regular", "Regular")],
                        default="once",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_incomes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incomes.incomecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Income",
                "verbose_name_plural": "Incomes",
                "ordering": ["-received_date"],
            },
        ),
    ]
