# Generated by Django 5.0.3 on 2026-03-16 16:25

from django.db import migrations


def migrate_income_data(apps, schema_editor):
    # Get old models from expenses app
    OldIncomeCategory = apps.get_model('expenses', 'IncomeCategory')
    OldIncome = apps.get_model('expenses', 'Income')
    
    # Get new models from incomes app
    NewIncomeCategory = apps.get_model('incomes', 'IncomeCategory')
    NewIncome = apps.get_model('incomes', 'Income')
    
    # Migrate income categories
    for old_category in OldIncomeCategory.objects.all():
        NewIncomeCategory.objects.create(
            id=old_category.id,
            name=old_category.name,
            description=old_category.description,
        )
    
    # Migrate incomes
    for old_income in OldIncome.objects.all():
        NewIncome.objects.create(
            id=old_income.id,
            name=old_income.name,
            description=old_income.description,
            amount=old_income.amount,
            received_date=old_income.received_date,
            category_id=old_income.category_id,
            source=old_income.source,
            frequency=old_income.frequency,
            user_id=old_income.user_id,
        )


def reverse_migrate(apps, schema_editor):
    # If we need to reverse, just delete the new data
    NewIncomeCategory = apps.get_model('incomes', 'IncomeCategory')
    NewIncome = apps.get_model('incomes', 'Income')
    
    NewIncome.objects.all().delete()
    NewIncomeCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0001_initial"),
        ("expenses", "0004_incomecategory_income"),  # Must run after expenses has the old models
    ]

    operations = [
        migrations.RunPython(migrate_income_data, reverse_migrate),
    ]

