# Generated by Django 5.0.3 on 2026-03-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0002_migrate_income_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
    ]
