# Generated by Django 5.0.3 on 2026-04-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0003_income_is_recurring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomecategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("salary", "Salary"),
                    ("freelance", "Freelance"),
                    ("investment", "Investment"),
                    ("business", "Business"),
                    ("gift", "Gift"),
                    ("bonus", "Bonus"),
                    ("child", "Child support"),
                    ("other", "Other"),
                ],
                max_length=128,
                unique=True,
            ),
        ),
    ]
