# Generated by Django 5.0.3 on 2026-06-14 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0004_alter_incomecategory_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeAmountChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_date", models.DateField()),
                ("note", models.CharField(blank=True, default="", max_length=256)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "income",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amount_changes",
                        to="incomes.income",
                    ),
                ),
            ],
            options={
                "verbose_name": "Income Amount Change",
                "verbose_name_plural": "Income Amount Changes",
                "ordering": ["-effective_date"],
                "unique_together": {("income", "effective_date")},
            },
        ),
    ]
