# Generated by Django 5.0.3 on 2026-07-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incomes", "0005_incomeamountchange"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="incomeamountchange",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="incomeamountchange",
            constraint=models.UniqueConstraint(
                fields=("income", "effective_date"), name="unique_income_effective_date"
            ),
        ),
    ]
