# Generated by Django 5.0.3 on 2026-07-26 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0011_alter_recurringexpensepricechange_unique_together_and_more"),
        ("stores", "0002_add_sports_type_serpa_decathlon"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnownStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Canonical store name (e.g. Lidl)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "ocr_variants",
                    models.TextField(
                        help_text="Comma-separated OCR variations, lowercase (e.g. lidl, l.dl, lid1, lidl stiftung)"
                    ),
                ),
                (
                    "group_label",
                    models.CharField(
                        default="Supermarket total",
                        help_text="Label used as expense name (e.g. Supermarket total, Drugstore total)",
                        max_length=100,
                    ),
                ),
                (
                    "store_type",
                    models.CharField(
                        choices=[
                            ("grocery", "Grocery Store"),
                            ("drugstore", "Drugstore"),
                            ("sports", "Sports Store"),
                            ("electronics", "Electronics Store"),
                            ("clothing", "Clothing Store"),
                            ("pet", "Pet Store"),
                            ("home", "Home Store"),
                        ],
                        default="grocery",
                        help_text="Type of store (grocery or drugstore)",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Category to auto-assign for receipts from this store",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="expenses.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Known Store",
                "verbose_name_plural": "Known Stores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Drugstore",
            fields=[],
            options={
                "verbose_name": "Drugstore",
                "verbose_name_plural": "Drugstores",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stores.knownstore",),
        ),
        migrations.CreateModel(
            name="GroceryStore",
            fields=[],
            options={
                "verbose_name": "Grocery Store",
                "verbose_name_plural": "Grocery Stores",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stores.knownstore",),
        ),
        migrations.CreateModel(
            name="SportStore",
            fields=[],
            options={
                "verbose_name": "Sport Store",
                "verbose_name_plural": "Sport Stores",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stores.knownstore",),
        ),
    ]
